// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_EQ4V80wAhUfqHmW4AaZKD5Z2c2T6DI',
    appId: '1:922040089807:web:2a2e3acb7e5847e3bdcbba',
    messagingSenderId: '922040089807',
    projectId: 'xerox-800f7',
    authDomain: 'xerox-800f7.firebaseapp.com',
    databaseURL: 'https://xerox-800f7-default-rtdb.firebaseio.com',
    storageBucket: 'xerox-800f7.appspot.com',
    measurementId: 'G-S3E50BN8RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4NxcoTUmhaFFrPIQ6RUw-AL4ik3FSjs',
    appId: '1:922040089807:android:b9bc9d55102860dcbdcbba',
    messagingSenderId: '922040089807',
    projectId: 'xerox-800f7',
    databaseURL: 'https://xerox-800f7-default-rtdb.firebaseio.com',
    storageBucket: 'xerox-800f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALODfSdlTkBnhRxPC1nV-Vq3Ji2qkO1RE',
    appId: '1:922040089807:ios:a526b2adbacd490dbdcbba',
    messagingSenderId: '922040089807',
    projectId: 'xerox-800f7',
    databaseURL: 'https://xerox-800f7-default-rtdb.firebaseio.com',
    storageBucket: 'xerox-800f7.appspot.com',
    iosClientId: '922040089807-u8m6s1fu6su0p0tg0hcadjar90rdoar3.apps.googleusercontent.com',
    iosBundleId: 'com.example.xerox',
  );
}
